def conta_letras(frase, contar="vogais"):
    total = 0;
    if contar == "vogais":
        total += frase.count("a")
        total += frase.count("e")
        total += frase.count("i")
        total += frase.count("o")
        total += frase.count("u")
        return total
    elif contar == "consoantes":
        total += frase.count("b")
        total += frase.count("B")
        total += frase.count("c")
        total += frase.count("C")
        total += frase.count("d")
        total += frase.count("D")
        total += frase.count("f")
        total += frase.count("F")
        total += frase.count("g")
        total += frase.count("G")
        total += frase.count("h")
        total += frase.count("H")
        total += frase.count("j")
        total += frase.count("J")
        total += frase.count("k")
        total += frase.count("K")
        total += frase.count("l")
        total += frase.count("L")
        total += frase.count("m")
        total += frase.count("M")
        total += frase.count("n")
        total += frase.count("N")
        total += frase.count("p")
        total += frase.count("P")
        total += frase.count("q")
        total += frase.count("Q")
        total += frase.count("r")
        total += frase.count("R")
        total += frase.count("s")
        total += frase.count("S")
        total += frase.count("t")
        total += frase.count("T")
        total += frase.count("v")
        total += frase.count("V")
        total += frase.count("w")
        total += frase.count("W")
        total += frase.count("x")
        total += frase.count("X")
        total += frase.count("y")
        total += frase.count("Y")
        total += frase.count("z")
        total += frase.count("Z")
        return total

    

print(conta_letras('programamos em python', 'vogais'))